name: Console-Redirection

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr
    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o testchecker *.c* ./sensor/*.c* ./sender/*.c*
      
    - name: run
      run: ./testchecker

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: dotnet build Battery-Parameter-Processor/BatteryParametersReceiver --configuration Debug
      
    - name: Run cmd
      run: ./testchecker | D:\a\stream-line-vrrenjith5\stream-line-vrrenjith5\\Battery-Parameter-Processor\BatteryParametersReceiver\bin\Debug\netcoreapp3.1\BatteryParametersReceiver.exe
      shell: cmd
